FROM node:22-alpine

RUN apk add --no-cache chromium
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

WORKDIR /app

COPY package.json package-lock.json ./

EXPOSE 9000

CMD ["sh", "-c", "npm ci && npx nest start --watch"]
